# Generated by Django 2.2.7 on 2019-11-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='ConfDiv',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='Conference',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='Division',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
