# Generated by Django 2.2.7 on 2019-12-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_auto_20191202_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoresalltime',
            name='AllTimeAverage',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='scoresalltime',
            name='AllTimeBest',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresalltime',
            name='AllTimeCorrect',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresalltime',
            name='AllTimePercentage',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='scoresalltime',
            name='AllTimeWorst',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
