# Generated by Django 2.2.13 on 2020-08-25 06:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0005_auto_20191204_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='GameID',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(20120101)]),
        ),
    ]
