# Generated by Django 2.2.13 on 2020-08-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0006_auto_20200825_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='FriendlyName',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
