# Generated by Django 2.2.13 on 2020-08-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0007_match_friendlyname'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='TeamsName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='FriendlyName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
