# Generated by Django 2.2.13 on 2020-09-02 16:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0008_auto_20200825_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='GameID',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(20100101)]),
        ),
    ]
