# Generated by Django 2.2.13 on 2021-03-17 09:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('predictor', '0009_auto_20200902_1619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scoresseason',
            options={'ordering': ['-SeasonScore', '-SeasonCorrect', '-BankerAverage', 'User'], 'verbose_name_plural': 'Season Scores'},
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=100, null=True)),
                ('Year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2100)])),
                ('Record', models.IntegerField()),
                ('Holders', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Records',
            },
        ),
    ]
