# Generated by Django 2.2.13 on 2021-03-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0010_auto_20210317_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Record',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
