# Generated by Django 2.2.13 on 2021-03-17 09:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0011_auto_20210317_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='Week',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(25)]),
            preserve_default=False,
        ),
    ]
