# Generated by Django 2.2.13 on 2021-03-17 09:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0012_record_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Week',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(25)]),
        ),
    ]
