# Generated by Django 2.2.13 on 2021-03-18 09:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0013_auto_20210317_0924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['Priority'], 'verbose_name_plural': 'Records'},
        ),
        migrations.AddField(
            model_name='record',
            name='Priority',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
            preserve_default=False,
        ),
    ]
