# Generated by Django 2.2.19 on 2021-04-13 07:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0014_auto_20210318_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='Week',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(18)]),
        ),
        migrations.AlterField(
            model_name='results',
            name='Week',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(18)]),
        ),
        migrations.AlterField(
            model_name='scoresweek',
            name='Week',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(18)]),
        ),
    ]
