# Generated by Django 2.2.19 on 2021-04-20 15:10

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0016_prediction_joker'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvgScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Season', models.IntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2100)])),
                ('AvgScores', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
    ]
