# Generated by Django 2.2.19 on 2021-05-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0017_avgscores'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['DateTime', 'AwayTeam'], 'verbose_name_plural': 'Matches'},
        ),
        migrations.AddField(
            model_name='team',
            name='Active',
            field=models.BooleanField(default=True),
        ),
    ]
