# Generated by Django 2.2.19 on 2021-08-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0018_auto_20210520_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Game', models.IntegerField()),
                ('HomeScore', models.IntegerField()),
                ('AwayScore', models.IntegerField()),
                ('Winning', models.CharField(choices=[('Home', 'Home'), ('Away', 'Away'), ('Tie', 'Tie')], max_length=4)),
            ],
        ),
    ]
