# Generated by Django 2.2.19 on 2021-08-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0019_livegame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livegame',
            name='AwayScore',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livegame',
            name='HomeScore',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livegame',
            name='Winning',
            field=models.CharField(blank=True, choices=[('Home', 'Home'), ('Away', 'Away'), ('Tie', 'Tie')], max_length=4, null=True),
        ),
    ]
