# Generated by Django 2.2.19 on 2021-08-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0020_auto_20210814_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='livegame',
            name='AwayTeam',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='livegame',
            name='HomeTeam',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
