# Generated by Django 2.2.19 on 2021-08-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0021_auto_20210816_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='livegame',
            name='Updated',
            field=models.BooleanField(default=False),
        ),
    ]
