# Generated by Django 2.2.19 on 2021-08-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0022_livegame_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='livegame',
            name='State',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
