# Generated by Django 4.2.17 on 2025-01-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0026_auto_20210827_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avgscores',
            name='AvgScores',
            field=models.JSONField(null=True),
        ),
    ]
