# Generated by Django 4.2.20 on 2025-07-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0027_alter_avgscores_avgscores'),
    ]

    operations = [
        migrations.CreateModel(
            name='PigskinConfig',
            fields=[
                ('Name', models.CharField(default='live', max_length=12, primary_key=True, serialize=False)),
                ('PredictWeek', models.IntegerField(default=1)),
                ('ResultsWeek', models.IntegerField(default=1)),
                ('PredictSeason', models.IntegerField(default=2025)),
                ('SundayLive', models.BooleanField(default=False)),
                ('RegistrationOpen', models.BooleanField(default=False)),
            ],
        ),
    ]
