# Generated by Django 2.2.7 on 2019-11-12 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191112_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='FavouriteTeam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predictor.Team'),
        ),
    ]
