services:
   django:
     build: .
     command: python manage.py runserver 0.0.0.0:8001
     restart: unless-stopped
     depends_on:
       - database
       - redis
       - celery
     volumes:
       - $PWD:/app
       - ./temp_data:/temp_data
     env_file:
       - app.env
     ports:                                                 
       - 8001:8001 

   database:
     image: postgres:16
     restart: unless-stopped
     environment:
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=PG_password
       - POSTGRES_DB=default
     volumes:
       - ./postgres-data:/var/lib/postgresql/data
     ports:
       - 5432:5432
    
   redis:
     image: 'redis:7.0'
     restart: unless-stopped
     environment:
       - ALLOW_EMPTY_PASSWORD=yes
     ports:
     - 6379:6379

   celery:
     build: .
     command: celery -A djangosite01 worker -l INFO --max-memory-per-child=512000 --concurrency=1
     restart: unless-stopped
     volumes:
      - $PWD:/app
     env_file:
      - app.env
     depends_on:
      - redis

   beat:
     build: .
     command: celery -A djangosite01 beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
     restart: unless-stopped
     volumes:
      - $PWD:/app
     env_file:
      - app.env
     depends_on:
      - redis