# Generated by Django 2.2.7 on 2019-11-14 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191112_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'My Custom User Class'},
        ),
    ]
