# Generated by Django 2.2.13 on 2020-08-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191114_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Full_Name',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
