# Generated by Django 2.2.13 on 2020-08-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Full_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
