# Generated by Django 2.2.19 on 2021-04-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210331_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='PickConfirmation',
            field=models.BooleanField(default=False, verbose_name='Pick Confirmation Emails'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Reminder48',
            field=models.BooleanField(default=True, verbose_name='48 Hour Reminder Emails'),
        ),
    ]
