# Generated by Django 2.2.19 on 2021-04-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210413_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='JokerUsed',
            field=models.IntegerField(blank=True, null=True, verbose_name='Joker Used'),
        ),
    ]
