# Generated by Django 2.2.19 on 2021-09-10 14:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_positions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Positions',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
