# Generated by Django 2.2.13 on 2020-09-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_posted'], 'verbose_name_plural': 'Updates'},
        ),
        migrations.AddField(
            model_name='post',
            name='short_content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
