# Generated by Django 2.1.7 on 2019-03-21 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='results',
            name='id',
        ),
        migrations.AlterField(
            model_name='results',
            name='GameID',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(2010010101)]),
        ),
    ]
