# Generated by Django 2.1.7 on 2019-03-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_results_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='Winner',
            field=models.CharField(max_length=4),
        ),
    ]
