# Generated by Django 2.1.7 on 2019-03-25 12:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0004_auto_20190321_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('Season', models.IntegerField(validators=[django.core.validators.MinValueValidator(2012), django.core.validators.MaxValueValidator(2050)])),
                ('Week', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(17)])),
                ('GameID', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(2010010101)])),
                ('DateTime', models.DateTimeField()),
                ('AwayTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AwayTeam_Schedule_Set', to='predictor.Team')),
                ('HomeTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HomeTeam_Schedule_Set', to='predictor.Team')),
            ],
        ),
        migrations.AlterModelOptions(
            name='results',
            options={'verbose_name_plural': 'Results'},
        ),
        migrations.AddField(
            model_name='results',
            name='Season',
            field=models.IntegerField(default=2012, validators=[django.core.validators.MinValueValidator(2012), django.core.validators.MaxValueValidator(2050)]),
            preserve_default=False,
        ),
    ]
