# Generated by Django 2.1.7 on 2019-03-25 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0005_auto_20190325_1226'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schedule',
            new_name='Match',
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'Matches'},
        ),
    ]
