# Generated by Django 2.1.7 on 2019-03-29 13:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('predictor', '0007_prediction'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prediction',
            unique_together={('User', 'Game')},
        ),
    ]
