# Generated by Django 2.1.7 on 2019-06-04 12:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('predictor', '0008_auto_20190329_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Week', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(17)])),
                ('Weekscore', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('Season', models.IntegerField(validators=[django.core.validators.MinValueValidator(2012), django.core.validators.MaxValueValidator(2050)])),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='prediction',
            name='Points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
