# Generated by Django 2.1.7 on 2019-06-06 16:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('predictor', '0009_auto_20190604_1239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scores',
            options={'verbose_name_plural': 'Scores'},
        ),
        migrations.AddField(
            model_name='team',
            name='Logo',
            field=models.ImageField(default='default.jpg', upload_to='logos'),
        ),
        migrations.AlterField(
            model_name='scores',
            name='Weekscore',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='scores',
            unique_together={('User', 'Week')},
        ),
    ]
