# Generated by Django 2.1.7 on 2019-06-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0010_auto_20190606_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='Logo',
            field=models.ImageField(default='football.png', upload_to='logos'),
        ),
    ]
