# Generated by Django 2.1.7 on 2019-06-06 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0011_auto_20190606_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='Logo',
        ),
    ]
