# Generated by Django 2.1.7 on 2019-06-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0012_remove_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='Logo',
            field=models.ImageField(default='football.png', upload_to='logos'),
        ),
    ]
