# Generated by Django 2.1.7 on 2019-06-10 19:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('predictor', '0015_prediction_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='Week',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='prediction',
            unique_together={('User', 'Week', 'Banker')},
        ),
    ]
