# Generated by Django 2.1.7 on 2019-06-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0016_auto_20190610_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='Week',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
