# Generated by Django 2.1.7 on 2019-06-12 11:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('predictor', '0019_auto_20190610_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='prediction',
            name='Banker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prediction',
            name='Week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='prediction',
            unique_together={('User', 'Week', 'Banker')},
        ),
    ]
