# Generated by Django 2.1.7 on 2019-06-12 11:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('predictor', '0020_auto_20190612_1150'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prediction',
            unique_together={('User', 'Game'), ('User', 'Week', 'Banker')},
        ),
    ]
