# Generated by Django 2.1.7 on 2019-06-12 12:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('predictor', '0021_auto_20190612_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prediction',
            old_name='Week',
            new_name='PredWeek',
        ),
        migrations.AlterUniqueTogether(
            name='prediction',
            unique_together={('User', 'PredWeek', 'Banker'), ('User', 'Game')},
        ),
    ]
