# Generated by Django 2.1.7 on 2019-06-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0022_auto_20190612_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='Banker',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
