# Generated by Django 2.1.7 on 2019-06-12 12:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('predictor', '0023_auto_20190612_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='Banker',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='prediction',
            unique_together={('User', 'Game')},
        ),
    ]
