# Generated by Django 2.1.7 on 2019-08-14 11:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('predictor', '0024_auto_20190612_1246'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scores',
            unique_together={('User', 'Week', 'Season')},
        ),
    ]
