# Generated by Django 2.1.7 on 2019-08-15 12:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('predictor', '0025_auto_20190814_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoresAllTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AllTimeScore', models.IntegerField()),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-AllTimeScore', 'User'],
                'verbose_name_plural': 'All Time Scores',
            },
        ),
        migrations.CreateModel(
            name='ScoresSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SeasonScore', models.IntegerField()),
                ('Season', models.IntegerField(validators=[django.core.validators.MinValueValidator(2012), django.core.validators.MaxValueValidator(2050)])),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-SeasonScore', 'User'],
                'verbose_name_plural': 'Season Scores',
            },
        ),
        migrations.CreateModel(
            name='ScoresWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Week', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(17)])),
                ('WeekScore', models.IntegerField()),
                ('Season', models.IntegerField(validators=[django.core.validators.MinValueValidator(2012), django.core.validators.MaxValueValidator(2050)])),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-WeekScore', 'User'],
                'verbose_name_plural': 'Weekly Scores',
            },
        ),
        migrations.AlterUniqueTogether(
            name='scores',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='scores',
            name='User',
        ),
        migrations.DeleteModel(
            name='Scores',
        ),
    ]
