# Generated by Django 2.1.7 on 2019-08-15 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('predictor', '0027_auto_20190815_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoresAllTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AllTimeScore', models.IntegerField()),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-AllTimeScore', 'User'],
                'verbose_name_plural': 'All Time Scores',
            },
        ),
    ]
