# Generated by Django 2.1.7 on 2019-10-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0029_auto_20191025_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banker',
            name='UserSeasonKey',
            field=models.CharField(max_length=10),
        ),
    ]
