# Generated by Django 2.1.7 on 2019-10-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0030_auto_20191025_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banker',
            name='UserSeasonKey',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
