# Generated by Django 2.1.7 on 2019-10-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0031_auto_20191025_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='banker',
            name='BankSeason',
            field=models.IntegerField(default=2019),
            preserve_default=False,
        ),
    ]
