# Generated by Django 2.1.7 on 2019-10-30 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0032_banker_bankseason'),
    ]

    operations = [
        migrations.AddField(
            model_name='banker',
            name='BankGame',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Match_Banker_Set', to='predictor.Match'),
            preserve_default=False,
        ),
    ]
