# Generated by Django 2.1.7 on 2019-10-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0033_banker_bankgame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banker',
            name='BankSeason',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banker',
            name='BankWeek',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
