name: Upload Static Files (Prod)

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete --cache-control max-age=86400,public
      env:
        AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_PROD }}
        AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_PROD }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_KEY_PROD }}
        SOURCE_DIR: 'predictor/static'
        DEST_DIR: 'static/predictor'